### ISSUE TITLE
Several questions about working with Doctrine relations

### ISSUE THREAD

**Issue by TrogWarZ** [nilportugues/symfony-jsonapi#27]
Hello.

How to use it with Doctrine relations (both types: Associations and Embedded)?

## src/FirstBundle/Entity/First.php
```php
<?php

namespace FirstBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SecondBundle\Entity\Second;

/**
 * @ORM\Entity(repositoryClass="FirstBundle\Repository\First")
 */
class First
{
    /** @ORM\Column(type="datetime") */
    private $created_at;
    /** @ORM\ManyToOne(targetEntity="SecondBundle\Entity\Second") */
    private $second;

    public function getCreatedAt() : \DateTime { return $this->created_at; }
    public function getSecond()    : Second    { return $this->second; }
}

?>
```

## src/FirstBundle/Entity/Embeddable/Contact.php
```php
<?php

namespace FirstBundle\Entity\Embeddable;

/** @ORM\Embeddable */
class Contact
{
    /** @ORM\Column(type="string", length=190) */
    private $city;
    public function getCity() : string { return $this->city; }
}

?>
```

## src/SecondBundle/Entity/Second.php
```php
<?php

namespace SecondBundle\Entity;

/**
 * @ORM\Entity(repositoryClass="SecondBundle\Repository\Second")
 */
class Second
{
}

?>
```

## src/FirstBundle/Resources/config/mapping/first.yml
```yaml
mapping:
    class: FirstBundle\Entity\First
    id_properties:
        - id
    hide_properties:
        - password
    urls:
        self: first_get_all
    relationships:
        second:
            self: we_dont_need_this
```

## src/FirstBundle/Resources/config/mapping/contact.yml
```yaml
mapping:
    class: FirstBundle\Entity\Embeddable\Contact
    id_properties: []
    hide_properties: []
    urls:
        self: we_dont_need_this
```

After using this project like this
```php
<?php

class SomeController
{
    public function getAllAction(ParamFetcher $paramFetcher) : Response
    {
        $all = $this->repository->findBy(
            $paramFetcher->get('search') ?? []
            , $paramFetcher->get('order') ?? []
            , $paramFetcher->get('limit')
            , $paramFetcher->get('offset')
        );

        return $this->response($this->serializer->serialize($all));
    }
}

?>
```

I get very strange response:
```json
{
    "data": [
        {
            "attributes": {
                "created_at": {
                    "date": "2016-11-15 12:52:55.000000",
                    "timezone": "Etc/UTC",
                    "timezone_type": 3
                },
                "id": 1905572758,
            },
            "id": "1905572758",
            "relationships": {
                "contact": {
                    "data": {
                        "id": "",
                        "type": "contact"
                    }
                },
                "payment": {
                    "data": {
                        "id": "",
                        "type": "payment"
                    }
                }
            },
            "type": "courier"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

## Questions:

1. How to include Second entity as relationship with First entity? What i'm doin wrong? Connected with #20 i think but there is no solution provided for me.
2. WTF is with \DateTime and created_at field? How to format this as string? Connected with #21 but not working for me )-:
3. Why embeddable entity Contact has id field? Don't need this and doesn't have. It has stored just as `contact_city` field in first table. No PK exists.
4. Why embeddable entity Contact don't have city field?

Thank you.
