### ISSUE TITLE
Mapping self url does not works

### ISSUE THREAD

**Issue by regniblod** [nilportugues/symfony-jsonapi#35]
I try to serialise an object but I get an error with the URL generation for the `self url` property.

This is my mapping:
```yaml
mapping:
  class: AppBundle\User
  alias: User
  id_properties:
    - id
  urls:
    self: get_user
```

This is `get_user` route definition (which works if I call it directly):
```
@Route(
    path="/user/{id}",
    name="get_user",
    requirements={"id": "\d+"}
)
```

And this is the error I get:
```
Parameter "id" for route "get_user" must match "\d+" ("{id}" given) to generate a corresponding URL.
```

If I change the mapping to something like
```yaml
# ...
  urls:
    self: route_without_parameters
# ...
```

I get a response but without any url referencing that route:
```json
{
  "data": {
    "type": "user",
    "id": "1",
    "attributes": {
        ...
    }
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```
