### ISSUE TITLE
Class name is serialized singular?

### ISSUE THREAD

**Issue by mmucklo** [nilportugues/symfony-jsonapi#6]
Any way to change the way the class name is serialized - e.g.

```
Article.php --> "type": "article"
```

versus

```
Article.php --> "type": "articles"
```

The examples on jsonapi.org seem to tend towards plural, although the spec is "agnostic" about it.

http://jsonapi.org/format/

**Comment by nilopc** [comment]
Class name is just transformed to an underscore version by default.  

It is possible to decide to what it's serialized by using the yml file during the mapping process. 
``` yml
mapping:
  class: Acme\Domain\Dummy\Post
  alias: messages #user defined plural.
...
```

This bundle does the hard part but does not try to force you anything allowing its user to be the one under control.
