### ISSUE TITLE
Choosing which properties to serialize?

### ISSUE THREAD

**Issue by joshuataylor** [nilportugues/symfony-jsonapi#8]
With the symfony serializer (or JMS), you can either use groups or config to dictate which properties should be serialized.

Can we do the same thing here?

**Comment by nilportugues** [comment]
Yes. See the example of the documentation:

- stop properties being serialized:  `hide_properties`
- renaming properties is done with:  `aliased_properties`

```yml
# app/config/serializer/acme_domain_dummy_post.yml

mapping:
  class: Acme\Domain\Dummy\Post
  alias: Message
  aliased_properties:
    author: author
    title: headline
    content: body
  hide_properties: []
  id_properties:
    - postId
  urls:
    self: get_post ## @Route name
    comments: get_post_comments ## @Route name
  relationships:
    author:
      related: get_post_author ## @Route name
      self: get_post_author_relationship  ## @Route name
```
